schema_version = "1.0.0"

id = "dragex"
version = "0.0.1"
name = "DragEx"
tagline = "Dragorn421's Exporter"
maintainer = "Dragorn421"
type = "add-on"

website = "https://github.com/Dragorn421/DragEx"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Dragorn421"]

platforms = [
    # PLATFORMS START
    "linux-x64",
    # PLATFORMS END
]

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# Observed behavior on Blender 4.2.0:
# If the wheel is missing, it is silently ignored and the import fails in the addon .py
# If the wheel is for the wrong python version, it is still loaded but doesn't work right?
# TODO observe with much newer 4.2.11
# 4.2.11:
# if the wheel is missing, it is silently ignored.
# It also seems like the installed wheel persists even when the wheel is deleted
# touching the blender_manifest.toml may be required to update the wheel installation?
wheels = [
    # WHEELS START
    "wheels/dragex_backend-0.0.1.dev1751887155-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
    # WHEELS END
]

[permissions]
files = "Write to disk"
