# This file was auto-generated from ../shader/defines.glsl by _defines_to_pydefines.py
# CC Color inputs
CC_C_0 = 0
CC_C_1 = 1
CC_C_COMB = 2
CC_C_TEX0 = 3
CC_C_TEX1 = 4
CC_C_PRIM = 5
CC_C_SHADE = 6
CC_C_ENV = 7
CC_C_CENTER = 8
CC_C_SCALE = 9
CC_C_COMB_ALPHA = 10
CC_C_TEX0_ALPHA = 11
CC_C_TEX1_ALPHA = 12
CC_C_PRIM_ALPHA = 13
CC_C_SHADE_ALPHA = 14
CC_C_ENV_ALPHA = 15
CC_C_LOD_FRAC = 16
CC_C_PRIM_LOD_FRAC = 17
CC_C_NOISE = 18
CC_C_K4 = 19
CC_C_K5 = 20

# CC Alpha inputs
CC_A_0 = 0
CC_A_1 = 1
CC_A_COMB = 2
CC_A_TEX0 = 3
CC_A_TEX1 = 4
CC_A_PRIM = 5
CC_A_SHADE = 6
CC_A_ENV = 7
CC_A_LOD_FRAC = 8
CC_A_PRIM_LOD_FRAC = 9

# Blender inputs
BLENDER_0 = 0
BLENDER_1 = 1
BLENDER_CLR_IN = 2
BLENDER_CLR_MEM = 3
BLENDER_CLR_BL = 4
BLENDER_CLR_FOG = 5
BLENDER_A_IN = 6
BLENDER_A_FOG = 7
BLENDER_A_SHADE = 8
BLENDER_1MA = 9
BLENDER_A_MEM = 10

# Geometry modes (some of these should be removed)
G_ZBUFFER = 1 << 0
G_SHADE = 1 << 1
G_CULL_FRONT = 1 << 2
G_CULL_BACK = 1 << 3
G_AMBOCCLUSION = 1 << 4
G_ATTROFFSET_Z = 1 << 5
G_ATTROFFSET_ST = 1 << 6
G_PACKED_NORMALS = 1 << 7
G_LIGHTTOALPHA = 1 << 8
G_LIGHTING_SPECULAR = 1 << 9
G_FRESNEL_COLOR = 1 << 10
G_FRESNEL_ALPHA = 1 << 11
G_FOG = 1 << 12
G_LIGHTING = 1 << 13
G_TEX_GEN = 1 << 14
G_TEX_GEN_LINEAR = 1 << 15
G_LOD = 1 << 16
G_SHADE_SMOOTH = 1 << 17
G_CLIPPING = 1 << 18

# Othermode modes
# L
G_MDSFT_ALPHACOMPARE = 0
G_MDSFT_ZSRCSEL = 2
G_MDSFT_RENDERMODE = 3
G_MDSFT_BLENDER = 16

G_AC_NONE = 0 << G_MDSFT_ALPHACOMPARE
G_AC_THRESHOLD = 1 << G_MDSFT_ALPHACOMPARE
G_AC_DITHER = 3 << G_MDSFT_ALPHACOMPARE

G_ZS_PIXEL = 0 << G_MDSFT_ZSRCSEL
G_ZS_PRIM = 1 << G_MDSFT_ZSRCSEL

# H
G_MDSFT_BLENDMASK = 0
G_MDSFT_ALPHADITHER = 4
G_MDSFT_RGBDITHER = 6

G_MDSFT_COMBKEY = 8
G_MDSFT_TEXTCONV = 9
G_MDSFT_TEXTFILT = 12
G_MDSFT_TEXTLUT = 14
G_MDSFT_TEXTLOD = 16
G_MDSFT_TEXTDETAIL = 17
G_MDSFT_TEXTPERSP = 19
G_MDSFT_CYCLETYPE = 20
G_MDSFT_COLORDITHER = 22  # HW 1.0
G_MDSFT_PIPELINE = 23

G_PM_1PRIMITIVE = 1 << G_MDSFT_PIPELINE
G_PM_NPRIMITIVE = 0 << G_MDSFT_PIPELINE

G_CYC_1CYCLE = 0 << G_MDSFT_CYCLETYPE
G_CYC_2CYCLE = 1 << G_MDSFT_CYCLETYPE
G_CYC_COPY = 2 << G_MDSFT_CYCLETYPE
G_CYC_FILL = 3 << G_MDSFT_CYCLETYPE

G_TP_NONE = 0 << G_MDSFT_TEXTPERSP
G_TP_PERSP = 1 << G_MDSFT_TEXTPERSP

G_TD_CLAMP = 0 << G_MDSFT_TEXTDETAIL
G_TD_SHARPEN = 1 << G_MDSFT_TEXTDETAIL
G_TD_DETAIL = 2 << G_MDSFT_TEXTDETAIL

G_TL_TILE = 0 << G_MDSFT_TEXTLOD
G_TL_LOD = 1 << G_MDSFT_TEXTLOD

G_TT_NONE = 0 << G_MDSFT_TEXTLUT
G_TT_RGBA16 = 1 << G_MDSFT_TEXTLUT
G_TT_IA16 = 2 << G_MDSFT_TEXTLUT

G_TF_POINT = 0 << G_MDSFT_TEXTFILT
G_TF_AVERAGE = 3 << G_MDSFT_TEXTFILT
G_TF_BILERP = 2 << G_MDSFT_TEXTFILT

G_TC_CONV = 0 << G_MDSFT_TEXTCONV
G_TC_FILTCONV = 5 << G_MDSFT_TEXTCONV
G_TC_FILT = 6 << G_MDSFT_TEXTCONV

G_CK_NONE = 0 << G_MDSFT_COMBKEY
G_CK_KEY = 1 << G_MDSFT_COMBKEY

G_CD_MAGICSQ = 0 << G_MDSFT_RGBDITHER
G_CD_BAYER = 1 << G_MDSFT_RGBDITHER
G_CD_NOISE = 2 << G_MDSFT_RGBDITHER
G_CD_DISABLE = 3 << G_MDSFT_RGBDITHER
G_CD_ENABLE = G_CD_NOISE

G_AD_PATTERN = 0 << G_MDSFT_ALPHADITHER
G_AD_NOTPATTERN = 1 << G_MDSFT_ALPHADITHER
G_AD_NOISE = 2 << G_MDSFT_ALPHADITHER
G_AD_DISABLE = 3 << G_MDSFT_ALPHADITHER

# Draw flags (custom for the shader)
DRAW_FLAG_DECAL = 1 << 0
DRAW_FLAG_ALPHA_BLEND = 1 << 1  # temporary, @TODO: proper blending emulation

# Tex flags
TEX_FLAG_MONO = 1 << 0
TEX_FLAG_4BIT = 1 << 1
TEX_FLAG_3BIT = 1 << 2

LOW_PRECISION = 64
