def get_value() -> int: ...

class FloatBufferThing:
    def __init__(self, length: int, value: float = 0.0) -> None: ...
    # memoryview should be memoryview[float] but that makes Pylance complain
    def __buffer__(self, flags: int, /) -> memoryview: ...
