import os

def set_log_file(path: str | os.PathLike, /) -> None: ...
def clear_log_file() -> None: ...
def flush() -> None: ...
def trace(message: str) -> None: ...
def debug(message: str) -> None: ...
def info(message: str) -> None: ...
def warn(message: str) -> None: ...
def error(message: str) -> None: ...
def fatal(message: str) -> None: ...
